### ISSUE TITLE
[Feature]: describe what builder/bundler is used in these kits

### ISSUE THREAD

**Issue by fwextensions** [thisdot/starter.dev#1163]
### Is your feature request related to a problem? Please describe.

I took a look at the site and the pages for several kits.  Nothing mentions what is used to build and bundle the code.  Is it vite?  Webpack?  Something else?  

### Describe the solution you'd like

Seems like the bundler should be listed in the tooling list of each kit.  Or if everything is using just one, then make that obvious on the homepage.

### Describe alternatives you've considered

N/A

**Comment by dustinsgoodman** [comment]
Thanks for the suggestion @fwextensions! We're looking into a few other site improvements right now too to better provide other information. I'll get this into that mix of thinking! Are there any other details you wish were present that aren't currently displayed?

**Comment by fwextensions** [comment]
It would be nice to show more of the tech stack on the home page.  I get that showing just 2 or 3 items is prettier, but React Router isn't listed in the React kit, for instance, which seems like it might be important.

The bulleted list of files and directories doesn't seem to add much value.   Maybe at the bottom of the page, in a more compact tree listing might be helpful, especially with links directly to the associated code.

The repo links on the details pages give a 404, e.g.: https://github.com/thisdot/starter.dev-showcases/tree/main/cra-rxjs-styled-components

But I guess they work from the GH icon on each kit on the homepage?  From that, I was able to glean the React kit uses webpack, it would seem.  Maybe all do?

At first glace, the site seemed really well-designed and useful, but the thinness of the details and the broken links put me off.  I probably would've just bounced, but I'm glad to see you're working on improvements.  Looking forward to what comes next!

**Comment by dustinsgoodman** [comment]
This is great feedback! Thank you. Each kit is designed to use its own stack based on the technology and what was available at the time of creation. Each contributor designs their own package so there's not necessarily a strong spec here to say everything is guaranteed to use X. The React kit in question uses create-react-app which does use webpack under the hood where as our Svelte, Qwik, and Solid kits all use Vite. 

I think in that particular case of that React kit saying webpack is used isn't truly fair because that's an implementation detail of the create-react-app tool. We might not be able to go that far with the tooling lists, but I think having the key pieces of information as you mentioned would be beneficial.

**Comment by lindakatcodes** [comment]
@fwextensions We just launched a new version of the website, taking into consideration some of your suggestions. We've added more of each kit's tooling to their respective cards and pages, and updated the kit pages to make things cleaner and ensure the links work as expected. 

Please let us know what you think! https://starter.dev/

**Comment by dustinsgoodman** [comment]
I'm going to close in hopes the above resolves this _but_ if there's more feedback still, let's talk!
