### ISSUE TITLE
[Bug]: the `--kit` flag does not always work

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#1272]
### What kit and version are you using?

n/a

### What browser are you using?

n/a

### What operating system are you using?

OSX

### Actual Behavior

When I copy the command from the website with the `--kit` flag, it doesn't always work out of the box. For example, I tried:
```
npm create @this-dot/starter --kit solidstart-tanstackquery-tailwind-modules
```

and was prompted to select my kit.

![image](https://github.com/thisdot/starter.dev/assets/1815379/ba7d2965-1d46-4b8a-8b3d-a9195b01edab)

### Expected Behavior

When I copy a command from the website, it should work

### Reproduction

Run:
```
npm create @this-dot/starter --kit solidstart-tanstackquery-tailwind-modules
```

**Comment by vyktoremario** [comment]
I think we discussed this on a [thread on slack](https://thisdot-labs.slack.com/archives/C02K0C2C484/p1671554762870049?thread_ts=1667576895.151839&cid=C02K0C2C484) sometime last year. The issue is that the `--kit` flag works, the command just needs to include `--`. Something like this: `npm create @this-dot/starter -- --kit solidstart-tanstackquery-tailwind-modules`. 

I will create a PR to correct the README for those commands that are broken

**Comment by dustinsgoodman** [comment]
Ah yes - it's more important to fix the READMEs then to ensure that they're correct. This one was wrong for instance:
![image](https://github.com/thisdot/starter.dev/assets/1815379/2108477a-f135-4dad-8396-dc1b5844434e)

**Comment by WillHutt** [comment]
This was completed in #1275 and the -- is needed on npm 7+
