### ISSUE TITLE
[Pods] - Update card designs for kits

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/starter.dev#1284]
We have decided to go with Option 1 for the design using the cards with logos (please see the team channel for the link to the figma file)

## Acceptance criteria 

- [x] Make the card titles more prominent
- [x] Add the showcases implementation from Figma including the link that jumps to the showcases list

**Comment by lindakatcodes** [comment]
We have some more requested feedback to handle for this ticket before the PR can be merged.

**Homepage**
All these tasks relate to the cards on the homepage
![Screen Shot 2023-06-30 at 6 58 38 PM](https://github.com/thisdot/starter.dev/assets/16214572/4bb1b9bd-cb4b-488e-9043-4b1630ef0dd5)

- [ ] Increase font weight of showcase title to be bold (at least 500)
- [ ] The title and icon list should both be left-aligned / in line with each other - can increase the icon size or spacing as needed to make it fit the card box better
- [ ] Need to investigate how the order of the icons for each card on the homepage shows up. Ideally we want the key tech items to show first, then the smaller tooling / other items.

**Logos and Tech Stacks**
- [ ] The Tanstack logo is too big for it's containing boxes and the edges bleed outside of the containing box - size needs to be shrunk
- [ ] If we can, update/replace the BullMQ logo? It's a little hard to read / tell what it is
- [ ] Solid and SolidStart - should use the full blue logo instead of the blue & green one it currently has
- [ ] DenoDB has their own icon in their repo, get and replace the current one
- [ ] Remove Oak from the tech stack list entirely (not really needed)

**Kit Page**
- [ ] The card heading on mobile - the showcase and source links should be the full width of the card (will need to hide the spacer div)
![Screen Shot 2023-06-30 at 7 02 24 PM](https://github.com/thisdot/starter.dev/assets/16214572/6ef9469f-f26d-4698-9a25-8c482999ab1b)

- [ ] On tablet sizes - when you click the "view showcases" link, the sticky header is over the section title, need to add scroll padding
![Screen Shot 2023-06-30 at 7 04 17 PM](https://github.com/thisdot/starter.dev/assets/16214572/b5867edb-2938-4ba6-abfb-4d3c0303984d)

**Kit Page - Showcases Section (bottom of page)**
![Screen Shot 2023-06-30 at 7 12 59 PM](https://github.com/thisdot/starter.dev/assets/16214572/2151a956-0175-4e94-90cf-4bcdaea5ebcd)
![Screen Shot 2023-06-30 at 7 12 53 PM](https://github.com/thisdot/starter.dev/assets/16214572/19e04047-b023-428f-8b25-c906e32dbde1)

- [ ] GitHub text should have a capital H
- [ ] Title should be base font size
- [ ] Repo and App links should be small font size, no font weight
- [ ] Remove the `hr`
- [ ] Light mode: set card background to be gray-100 and border to be gray-400
- [ ] Light mode: set icon border to be gray-400
