### ISSUE TITLE
Upgrade next-chakra-ui to Next 13

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#1295]
# Acceptance
- [x] upgrade kit to latest Next 13.4 version
- [ ] Convert kit to use Next.js app directory

**Comment by iansamz** [comment]
@dustinsgoodman @Atrophius 

Due to these comments: https://github.com/chakra-ui/chakra-ui/issues/7649#issuecomment-1571777824
I dont think we will be capable to convert this app directory at the moment as one wont be able to use server components.

I think it would be better to move forward with pages directory
